<../../../mkconfig

# Windowing applications - no wlua for now
# Will be replaced with generic FFI-based Lua shell

TARG=

MODULES=

DISBIN=$ROOT/dis

install:V:
	# Nothing to install

clean:V:
	rm -f *.dis *.sbl
