<../../../mkconfig

DISBIN=$ROOT/dis/wm

MODULES=\
	wm.m\
	wmsrv.m\

# Build rule for .b files
%.dis:	%.b
	limbo -I$ROOT/module -gw $stem.b

all:V:
	limbo -I$ROOT/module -gw *.b

install:V:	install-$SHELLTYPE

install-rc install-nt:V:	all
	for(i in *.dis){
		cp $i $DISBIN/$i
	}

install-sh:V:	all
	for i in *.dis
	do
		cp $i $DISBIN/$i
	done

clean:V:
	rm -f *.dis *.sbl

nuke:V:	clean
	rm -f $DISBIN/*.dis
