<../../../mkconfig

# Windowing applications

DISBIN=$ROOT/dis/wm

MODULES=\
	wm.m\
	wmsrv.m\

all:V:
	sh build-all.sh

install:V:	all
	sh install-all.sh

clean:V:
	rm -f *.dis *.sbl

nuke:V:	clean
	rm -f $DISBIN/*.dis
