<../../mkconfig

# Commands - build all .b files automatically

DISBIN=$ROOT/dis

all:V:
	sh build-all.sh

install:V:	all
	sh install-all.sh

clean:V:
	find . -name '*.dis' -delete
	find . -name '*.sbl' -delete

nuke:V:	clean
	find $DISBIN -name '*.dis' -delete 2>/dev/null || true
